// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dbMigration;

#nullable disable

namespace dbMigration.migrations
{
    [DbContext(typeof(ethDB))]
    [Migration("20250101181540_In10")]
    partial class In10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dbMigration.models.EthBlocksEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("baseFeePerGas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gasLimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gasUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numberHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numberInt")
                        .HasColumnType("int");

                    b.Property<DateTime>("timestampNormal")
                        .HasColumnType("datetime2");

                    b.Property<string>("timestampUnix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EthBlocksEntities");
                });

            modelBuilder.Entity("dbMigration.models.EthSwapsETH_Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EthIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EthOut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenOut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("blockNumberEndInt")
                        .HasColumnType("int");

                    b.Property<int>("blockNumberStartInt")
                        .HasColumnType("int");

                    b.Property<string>("from")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isBuyEth")
                        .HasColumnType("bit");

                    b.Property<bool>("isBuyToken")
                        .HasColumnType("bit");

                    b.Property<string>("pairAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("priceETH_USD")
                        .HasColumnType("float");

                    b.Property<double>("priceTokenInETH")
                        .HasColumnType("float");

                    b.Property<string>("to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("txsHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("blockNumberEndInt");

                    b.HasIndex("blockNumberStartInt");

                    b.ToTable("EthSwapsETH_TokenEntities");
                });

            modelBuilder.Entity("dbMigration.models.EthSwapsETH_USD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EthIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EthOut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenOut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("blockNumberInt")
                        .HasColumnType("int");

                    b.Property<string>("from")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isBuyDai")
                        .HasColumnType("bit");

                    b.Property<bool>("isBuyEth")
                        .HasColumnType("bit");

                    b.Property<string>("pairAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("priceEthInUsd")
                        .HasColumnType("float");

                    b.Property<string>("to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("txsHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("blockNumberInt");

                    b.ToTable("EthSwapsETH_USDEntities");
                });

            modelBuilder.Entity("dbMigration.models.EthTokenInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Decimals")
                        .HasColumnType("int");

                    b.Property<string>("NameLong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameShort")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    b.ToTable("EthTokenInfoEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
